In [34]:
import pandas as pd
URL = 'https://raw.githubusercontent.com/turgonboyevbotir/works/main/Tashkent%20city/Tashkent%20city.csv'
df = pd.read_csv(URL)
df = df.drop('location', axis=1)
df.head()

Unnamed: 0           district  rooms  size  level  max_levels  price
0          81        Учтепинский      1  20.0      3           9  14500
1         110        Яшнободский      1  20.0      3           3  12500
2         473      Яккасарайский      1  20.0      2           4  14500
3         739  Мирзо-Улугбекский      1  16.0      1           4  18000
4         745  Мирзо-Улугбекский      1  16.0      1           4  18000

In [37]:
from sklearn.model_selection import train_test_split
train_set,  test_set = train_test_split(df, test_size=0.07, random_state=20)

x_train = train_set.drop('price', axis=1)
y = train_set['price'].copy()
x_num = x_train.drop('district', axis=1)

In [36]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [38]:
#Sonli konver
num_pipeline = Pipeline([
                         ('imputer', SimpleImputer(strategy='median')),
                         ('std_scaler', StandardScaler())
])

num_pipeline.fit_transform(x_num)

array([[ 1.84175974, -0.38470645,  0.37018801, -1.24905492, -0.19838652],
       [-0.68845199,  4.78574824, -1.31786932, -0.54370626, -1.31868686],
       [-0.44953769, -0.38470645,  0.37018801, -0.54370626, -0.19838652],
       [ 0.9022518 ,  0.35392993, -2.65054617, -0.54370626,  0.36176365],
       [ 0.7502586 , -0.38470645,  0.37018801, -1.24905492, -0.19838652],
       [-0.44858773, -0.38470645,  0.7255685 , -0.54370626, -0.19838652],
       [-1.12210758, -0.38470645,  0.7255685 , -0.54370626,  0.36176365],
       [-1.65598368, -0.38470645,  0.7255685 ,  0.1616424 , -0.75853669],
       [-0.24197198, -0.38470645,  0.37018801, -0.54370626, -0.19838652],
       [ 0.36505085, -0.38470645,  0.37018801,  0.1616424 , -0.19838652],
       [ 0.51941894,  2.56983909, -2.15301348, -0.54370626, -1.31868686],
       [ 0.36077604, -0.38470645,  0.37018801,  0.86699106, -0.19838652],
       [ 1.16301512, -0.38470645, -0.16288273,  0.1616424 , -0.19838652],
       [-0.44526288, -0.38470645,  0.3

In [43]:
from sklearn.compose import ColumnTransformer
num_attributes = list(x_num)
cat_attribs = ['district'] 

full_pipeline = ColumnTransformer([
                                   ('num', num_pipeline, num_attributes),
                                   ('cat', OneHotEncoder(), cat_attribs)
])

In [44]:
x_prepared = full_pipeline.fit_transform(x_train)

In [46]:
#Yangi model yaratamiz 
from sklearn.linear_model import LinearRegression
LR_modes = LinearRegression()

LR_modes.fit(x_prepared, y)

LinearRegression()

In [47]:
test_data = x_train.sample(5)
test_data

Unnamed: 0           district  rooms  size  level  max_levels
47        7407        Яшнободский      3  15.0      7           9
35        4984        Яшнободский      1  20.0      2           4
24        3087        Яшнободский      1  18.0      2           4
17        2650  Мирзо-Улугбекский      1  18.0      2           4
28        4337        Мирабадский      3   5.0      4           5

In [49]:
test_label = y.loc[test_data.index]
test_label

47    50000
35    14000
24    11000
17    14000
28    46600
Name: price, dtype: int64

In [50]:
test_data_prepared = full_pipeline.transform(test_data)
test_data_prepared

array([[ 1.80993616,  1.09256632, -0.16288273,  2.98303705,  2.60236434,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.65906268, -0.38470645,  0.7255685 , -0.54370626, -0.19838652,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ],
       [-0.24197198, -0.38470645,  0.37018801, -0.54370626, -0.19838652,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ],
       [-0.44953769, -0.38470645,  0.37018801, -0.54370626, -0.19838652,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.35175144,  1.09256632, -1.93978519,  0.86699106,  0.36176365,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.  

In [51]:
predicted_data = LR_modes.predict(test_data_prepared)
predicted_data

array([58646.80282256, 14036.91637241, 11158.68931652, 15154.04019742,
       34990.48659538])

In [52]:
pd.DataFrame({'Prognoz':predicted_data, 'Real baxosi': test_label})

Prognoz  Real baxosi
47  58646.802823        50000
35  14036.916372        14000
24  11158.689317        11000
17  15154.040197        14000
28  34990.486595        46600

In [53]:
test_set

Unnamed: 0           district  rooms  size  level  max_levels  price
45        6873  Мирзо-Улугбекский      1  20.0      1           4  17500
4          745  Мирзо-Улугбекский      1  16.0      1           4  18000
44        6338       Чиланзарский      1  20.0      3           9  14500
49        7505        Учтепинский      1  18.0      3           4  16000

In [55]:
x_test = test_set.drop('price', axis=1)
y_test = test_set['price'].copy()

In [56]:
x_test_prepared = full_pipeline.transform(x_test)
y_predicted = LR_modes.predict(x_test_prepared)

In [57]:
import numpy as np

In [58]:
#Birinchi tekshirish
from sklearn.metrics import mean_squared_error
lin_mse = mean_squared_error(y_test, y_predicted)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

4680.422071266934


In [61]:
#Ikkinchi tekshirish
x = df.drop('price', axis=1)
y = df['price'].copy()

x_prepared = full_pipeline.transform(x)

In [62]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(LR_modes, x_prepared, y, scoring="neg_mean_squared_error", cv=8)
LR_rmse_scores = np.sqrt(-scores)

In [63]:
def display_scores(scores):
  print(f"Scores : {scores}")
  print("Mean:", scores.mean())
  print("Std.dev:", scores.std())

display_scores(LR_rmse_scores)

Scores : [12628.99933614 35564.49221113 11028.07951462  4790.58806385
  7493.1238669   4876.70533105  5262.27261631 16252.77776605]
Mean: 12237.129838255583
Std.dev: 9635.141976061028


In [69]:
#Modelni saqlash

import pickle

filename = 'LR_model.pkl'
with open (filename, 'wb') as file:
  pickle.dump(LR_modes, file)

In [70]:
#Modelni qayta o'qib olamiz

with open(filename, 'rb') as file:
    model = pickle.load(file)

In [71]:
#Modelni qayta ishlatib ko'ramiz

scores = cross_val_score(model, x_prepared, y, scoring="neg_mean_squared_error", cv=5)
LR_rmse_scores = np.sqrt(-scores)
display_scores(LR_rmse_scores)

Scores : [10566.48052758 26276.50624087  6864.84573077  7102.74429228
 14195.99392568]
Mean: 13001.314143438172
Std.dev: 7155.917420029917
